// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj7hj4h-eEFTGKsubuStRpJIGo_C5ppco',
    appId: '1:47979546381:web:c01038bf141dea485cd244',
    messagingSenderId: '47979546381',
    projectId: 'doc-scheduler-6e8de',
    authDomain: 'doc-scheduler-6e8de.firebaseapp.com',
    storageBucket: 'doc-scheduler-6e8de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbJzXf-CHv6vmBbKbK7GS2S-_PneY1leE',
    appId: '1:47979546381:android:2f57d3ed08e74b325cd244',
    messagingSenderId: '47979546381',
    projectId: 'doc-scheduler-6e8de',
    storageBucket: 'doc-scheduler-6e8de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATzp7Hn91ux5_54qqZy6DHT5-MqwE6rFE',
    appId: '1:47979546381:ios:63dd18af98a7354d5cd244',
    messagingSenderId: '47979546381',
    projectId: 'doc-scheduler-6e8de',
    storageBucket: 'doc-scheduler-6e8de.appspot.com',
    iosBundleId: 'com.example.docscheduler',
  );
}
